# Generated by Django 3.2.9 on 2022-06-24 17:42

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ISCO',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('Group', models.TextField()),
                ('Name', models.TextField()),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JobAnalysis',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('Career', models.TextField()),
                ('HardSkill', models.TextField()),
                ('SoftSkill', models.TextField()),
                ('Personality', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('Firstname', models.CharField(max_length=200, null=True)),
                ('Lastname', models.CharField(max_length=200, null=True)),
                ('skill', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
