# Generated by Django 3.2.9 on 2022-06-24 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='skill',
            new_name='skills',
        ),
    ]
